#!/usr/bin/env bash
# install load balancer

sudo apt-get update -y 
sudo apt-get install -y haproxy 

server_config=\
"
frontend http_frontend
    bind *:80
    default_backend http_backend

backend http_backend
    balance roundrobin
    server 531182-web-01 54.162.77.178:80 check
    server 531182-web-02 52.87.216.60:80 check
"

echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

sudo service haproxy start
sudo service haproxy restart
