#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passing the argument `start`:
#     1. Starting manage_my_process
#     2. Creating a file containings its PID in /var/run/my_process.pid
#     3. Displaying "manage_my_process started"
#   When passing the argument `stop`:
#     1. Stoping manage_my_process
#     2. Deleting the file /var/run/my_process.pid
#     3. Displaying "manage_my_process stopped"
#   When passingthe argument `restart`:
#     1. Stoping manage_my_process
#     2. Deleting the file /var/run/my_process.pid
#     3. Starting manage_my_process
#     4. Creating a file containing its PID in /var/run/my_process.pid
#     5. Displaying "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi

