#!/usr/bin/env bash
# Parsing the Apache log files in list format.
#   Grouping the visitors by IP and HTTP status code.
#   Displaying the number of occurrences, IP, and HTTP status
#+  code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn

